django_project/urls.py
from django.contrib import admin
from django.urls import include, path       # Step 2.a import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls'))  # Step 2.b Create path to urls.py in the app
]

landing_page/urls.py
# Step 3. Create the urls.py module and all the paths for the application

from django.urls import include, path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('home', views.home_redirect, name='home'),	# redirect user to home page
	path('login', views.login_view, name='login'),
	path('register', views.register, name='register'),

	# Projects Paths
	path('workboard/', include('workboard.urls', namespace='workboard'), name='workboard'),	# link to the workboard app
	path('social/', include('social.urls', namespace='social'), name='social'),
	path('mail-client/', include('mail_client.urls', namespace='mail_client'), name='mail_client'),
	path('e-commerce/', include('e_commerce.urls', namespace='commerce'), name='commerce')
]

social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('guest-path', views.guest_path, name='guest-path'),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
    path("profile-page/<str:username>", views.profile_page, name="profile-page"),
    path("following/<str:username>", views.following_page, name="following"),

    # API Routes
    path("save-new-post", views.save_new_post, name="save-new-post"),
    path("save-edited-post/<int:postID>", views.save_edited_post, name="save-edited-post"),
    path("follow", views.follow, name="follow"),
    path("unfollow", views.unfollow, name="unfollow"),
    path("like-post/<int:postID>", views.like_post, name="like-post")
]

app_name = 'social'

landing_page/models.py
from django.db import models

# Import the following:
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    number_of_followers = models.IntegerField(default=0)
    number_of_followings = models.IntegerField(default=0)

    def __str__(self):
        return f"User: {self.id}, {self.username}, followers: {self.number_of_followers}, following: {self.number_of_followings}"

landing_page/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from .models import User

# Create your views here.
def index(request):
	return render(request, 'landing_page/index.html')


def home_redirect(request):
	return HttpResponseRedirect(reverse('index'))


def login_view(request):
	return render(request, 'landing_page/login.html')


def register(request):
	if request.method == 'POST':
		username = request.POST['username']
		email = request.POST['email']

		# Ensure password matches confirmation
		password = request.POST['password']
		confirmation = request.POST['confirmation']
		if password != confirmation:
			return render(request, 'landing_page/register.html', {
				'message': "Passwords must match."
			})

		# Attempt to create new user
		try:
			user = User.objects.create_user(username, email, password)
			user.save()
		except IntegrityError:
			return render(request, 'landing_page/register.html', {
				'message': "username already taken."
			})
		login(request, user)
		return HttpResponseRedirect(reverse('index'))
	
	else:
		return render(request, 'landing_page/register.html')

landing_page/templates/landing_page/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charste="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Cody Miu{% block title %}{% endblock %}</title>
		<!-- Add icon logo in the tab bar -->
		<link rel="icon" href="{% static 'landing_page/logos/cm-logo.png' %}">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		
		<link rel="stylesheet" href="{% static 'landing_page/css/lightbox.min.css' %}">
		<link rel="stylesheet" href="{% static 'landing_page/css/styles.css' %}">
		
		<script src="{% static 'landing_page/js/index.js' %}"></script>
	</head>	
	<body>

		<nav>
			<div title="Hello!" class="main-logo right-left-animation">&lt; cody &gt;</div>
	
			<ul class="navbar-list inline-list">	<!-- Remove bullet points and add spaces between the links -->
				<li><button class="navbar-link" id="projects-btn" title="View Projects">Projects</button></li>
				<li><button class="navbar-link" id="resume-btn" title="View Resume">Resume</button></li>
				<li><button class="navbar-link" id="contact-btn" title="View Contact info">Contact</button></li>
			</ul>

			<div id="dropdown">
				<button id="dropdown-btn"><img src="{% static 'landing_page/logos/dropdown_white_38.png' %}"></button>
				<div id="dropdown-content" class="column-align">
					<button id="mobile-projects-btn">Projects</button>
					<button id="mobile-resume-btn">Resume</button>
					<button id="mobile-contact-btn">Contact</button>
				</div>
			</div>
		</nav>

		<div id="darken-overlay"></div>
		
		<div id="pdf-modal">
			<iframe src="{% static 'landing_page/Cody_Miu_Developer_Resume.pdf' %}"></iframe>
			<img src="{% static 'landing_page/logos/close-btn_24.png' %}" width="24" alt="X">
		</div>
		
		<section id="main-container">
		
		<header>
			<div id="title-container">
				<h1 id="title"><span class="multi-line-type">Software Developer</span><span id="title-dot">.</span></h1>
				<p id="tools">JavaScript | TypeScript | React | Python | Node.js | Django | HTML | CSS | Tailwind | SQL</p>
			</div>

			<div id="header-second-container">
				<div id="intro" class="fade-in-animation">
					<p>Hello &#128515; I'm a software developer from Montreal, Canada who enjoys creating web applications. Although I have started with Java, C and Assembly during my bachelor in Information Systems at McGill University, I found my passion after graduation with full-stack tools such as Python and JavaScript.<br><br>
					With a diverse background, I am eager to tackle any technical project.
					</p>
				
					<div id="logo-links">
						<a href="https://github.com/Cody06" target="_blank" >
							<img src="{% static 'landing_page/logos/github_square_50.png' %}" width="50" 
							alt="Github link" class="up-down-animation">
						</a>
						<a href="http://www.linkedin.com/in/cody-miu" target="_blank">
							<img src="{% static 'landing_page/logos/linkedin_square_50.png' %}" width="50"
							alt="LinkedIn link" class="up-down-animation">
						</a>
					</div>
				</div>

				<div id="header-logo">
					<img src="{% static 'landing_page/logos/fullstack-development-orange.png' %}">
				</div>
			</div>

		</header>

		<main id="projects" class="fade-in-animation">
			<p>PROJECTS</p>
	
			<!--____________________________ Workboard ____________________________-->
			<div class="project-container up-down-animation">

				<div class="project-img">
					<img src="{% static 'landing_page/imgs/laptop_520.png' %}" class="laptop-img">
					<div class="screenshot-position">
						<img src="{% static 'landing_page/imgs/workboard_414.png' %}" class="project-screenshot">
					</div>
				</div>

				<div class="project-info">
					<p class="project-title">Workboard <span>2021</span></p>
					<div class="project-tools text-muted">
						<div>Python</div>
						<div>Django</div>
						<div>JavaScript</div>
						<div>HTML</div>
						<div>CSS</div>
						<div>Bootstrap</div>
						<div>API</div>
					</div>
					<p class="project-description">Workboard is a project managing application. Users can create project boards with different columns and move their tasks between them.</p>
					<div class="project-btns">
						<a href="{% static 'landing_page/gallery_workboard/workboard-1.png' %}" data-lightbox="workboard-set" data-title="Workboard Home Page" class="preview-btn">Preview</a>
						<a href="{% url 'workboard:guest-path' %}" target="_blank" class="project-btn">Visit Workboard</a>
					</div>
				</div>
			</div>
			<!--____________________________ Social ____________________________-->
			<div class="project-container up-down-animation">	
				<div class="project-img">
					<img src="{% static 'landing_page/imgs/laptop_520.png' %}" class="laptop-img">
					<div class="screenshot-position">
						<img src="{% static 'landing_page/imgs/social_414.png' %}" class="project-screenshot">
					</div>
				</div>
				<div class="project-info">
					<p class="project-title">Social Networking Platform <span>2021</span></p>
					<div class="project-tools text-muted">
						<div>Python</div>
						<div>Django</div>
						<div>JavaScript</div>
						<div>HTML</div>
						<div>CSS</div>
						<div>Bootstrap</div>
					</div>
					<p class="project-description">This platform allows users to create posts and follow other users. An implementation of the "like" button is also present.</p>
					<div class="project-btns">
						<a href="{% static 'landing_page/gallery_social/social-1.png' %}" data-lightbox="social-set" data-title="Social Home Page" class="preview-btn">Preview</a>
						<a href="{% url 'social:guest-path' %}" target="_blank" class="project-btn">Visit Social</a>
					</div>
				</div>
			</div>
			<!--____________________________ E-Commerce ____________________________-->
			<div class="project-container up-down-animation">	
				<div class="project-img">
					<img src="{% static 'landing_page/imgs/laptop_520.png' %}" class="laptop-img">
					<div class="screenshot-position">
						<img src="{% static 'landing_page/imgs/commerce_414.png' %}" class="project-screenshot">
					</div>
				</div>
				<div class="project-info">
					<p class="project-title">E-Commerce Platform <span>2021</span></p>
					<div class="project-tools text-muted">
						<div>Python</div>
						<div>Django</div>
						<div>JavaScript</div>
						<div>HTML</div>
						<div>CSS</div>
						<div>Bootstrap</div>
					</div>
					<p class="project-description">This is an e-commerce platform where users can post items for auction and bid on posted ones. A comment section is also implemented.</p>
					<div class="project-btns">
						<a href="{% static 'landing_page/gallery_commerce/commerce-1.png' %}" data-lightbox="commerce-set" data-title="E-Commerce Home Page" class="preview-btn">Preview</a>
						<a href="{% url 'commerce:guest-path' %}" target="_blank" class="project-btn">Visit E-Commerce</a>
					</div>
				</div>
			</div>
			<!--____________________________ Email ____________________________-->
			<div class="project-container up-down-animation">	
				<div class="project-img">
					<img src="{% static 'landing_page/imgs/laptop_520.png' %}" class="laptop-img">
					<div class="screenshot-position">
						<img src="{% static 'landing_page/imgs/email_414.png' %}" class="project-screenshot">
					</div>
				</div>
				<div class="project-info">
					<p class="project-title">Email Client <span>2021</span></p>
					<div class="project-tools text-muted">
						<div>Python</div>
						<div>Django</div>
						<div>JavaScript</div>
						<div>HTML</div>
						<div>CSS</div>
						<div>Bootstrap</div>
						<div>API</div>
					</div>
					<p class="project-description">This is an email client where users can send, receive and archive emails through a built-in API. The application focuses on User Interfaces where everything runs on one html page.</p>
					<div class="project-btns">
						<a href="{% static 'landing_page/gallery_mail_client/email-1.png' %}" data-lightbox="email-set" data-title="Email Home Page - Inbox" class="preview-btn">Preview</a>
						<a href="{% url 'mail_client:guest-path' %}" target="_blank" class="project-btn">Visit Email</a>
					</div>
				</div>
			</div>
		</main>
		</section>
		<!-- All images when clicking preview -->
		<div id="preview-images">
		<a href="{% static 'landing_page/gallery_workboard/workboard-2.png' %}" data-lightbox="workboard-set" data-title="Create a new board"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-3.png' %}" data-lightbox="workboard-set" data-title="Board Page (empty view)"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-4.png' %}" data-lightbox="workboard-set" data-title="Add a new column"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-5.png' %}" data-lightbox="workboard-set" data-title="Board with columns and cards"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-6.png' %}" data-lightbox="workboard-set" data-title="Edit column's name"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-7.png' %}" data-lightbox="workboard-set" data-title="Edit card's contents"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-8.png' %}" data-lightbox="workboard-set" data-title="Drag and drop cards between columns"></a>
		<a href="{% static 'landing_page/gallery_workboard/workboard-9.png' %}" data-lightbox="workboard-set"
		data-title="Archive board"></a>

		<a href="{% static 'landing_page/gallery_social/social-2.png' %}" data-lightbox="social-set" data-title="User's profile"></a>
		<a href="{% static 'landing_page/gallery_social/social-3.png' %}" data-lightbox="social-set" data-title="Other user's profile"></a>
		<a href="{% static 'landing_page/gallery_social/social-4.png' %}" data-lightbox="social-set" data-title="User's following list"></a>

		<a href="{% static 'landing_page/gallery_mail_client/email-2.png' %}" data-lightbox="email-set" data-title="Email view"></a>
		<a href="{% static 'landing_page/gallery_mail_client/email-3.png' %}" data-lightbox="email-set" data-title="Compose new email"></a>
		<a href="{% static 'landing_page/gallery_mail_client/email-4.png' %}" data-lightbox="email-set" data-title="Email view with replies"></a>
		<a href="{% static 'landing_page/gallery_mail_client/email-5.png' %}" data-lightbox="email-set" data-title="List of sent emails"></a>

		<a href="{% static 'landing_page/gallery_commerce/commerce-2.png' %}" data-lightbox="commerce-set" data-title="Categories List"></a>
		<a href="{% static 'landing_page/gallery_commerce/commerce-3.png' %}" data-lightbox="commerce-set" data-title="Items selected by category"></a>
		<a href="{% static 'landing_page/gallery_commerce/commerce-4.png' %}" data-lightbox="commerce-set" data-title="Item's page"></a>
		<a href="{% static 'landing_page/gallery_commerce/commerce-5.png' %}" data-lightbox="commerce-set" data-title="Create new listing"></a>
		</div>
		
		<footer class="fade-in-animation">
			<table id="contact-info">
				<tr>
					<th colspan="2">Get in touch</th>
				<tr>
					<td><img src="{% static 'landing_page/logos/location_pointer_24.png' %}"></td>
					<td>Montreal, QC <br>Canada</td>
				</tr>
				<tr>
					<td><img src="{% static 'landing_page/logos/email_24.png' %}"></td>
					<td><a href="mailto: cody.miu@gmail.com" target="_blank">cody.miu@gmail.com</a></td>
				</tr>
					<td><img src="{% static 'landing_page/logos/linkedin_round_24.png' %}"></td>
					<td><a href="http://www.linkedin.com/in/cody-miu" target="_blank">Linkedin</a></td>
				</tr>
			</table>
		</footer>
	</body>
	<script src="{% static 'landing_page/js/lightbox-plus-jquery.min.js' %}"></script>
</html>
<!-- Preview images is done with Lightbox source: https://lokeshdhakar.com/projects/lightbox2/ -->

landing_page/templates/landing_page/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Login</title>
	</head>
	<body>
		<h2>Log in</h2>

		{% if message %}
        	<div>{{ message }}</div>
    	{% endif %}

	    <form action="{% url 'login' %}" method="post">
	        {% csrf_token %}
	        <div class="form-group">
	            <input autofocus class="form-control" type="text" name="username" placeholder="Username" required>
	        </div>
	        <div class="form-group">
	            <input class="form-control" type="password" name="password" placeholder="Password" required>
	        </div>
	        <input class="btn btn-primary" type="submit" value="Login">
	    </form>


		<a href="{% url 'index' %}">Back to Home Page</a>
	</body>
</html>

landing_page/templates/landing_page/register.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Login</title>
	</head>
	<body>
		<h2>Register</h2>

		{% if message %}
        	<div>{{ message }}</div>
    	{% endif %}

	    <form action="{% url 'register' %}" method="post">
	        {% csrf_token %}
	        <div class="form-group">
	            <input class="form-control" autofocus type="text" name="username" placeholder="Username" required>
	        </div>
	        <div class="form-group">
	            <input class="form-control" type="email" name="email" placeholder="Email Address">
	        </div>
	        <div class="form-group">
	            <input class="form-control" type="password" name="password" placeholder="Password" required>
	        </div>
	        <div class="form-group">
	            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
	        </div>
	        <input class="btn btn-primary" type="submit" value="Register">
	    </form>


		<a href="{% url 'index' %}">Back to Home Page</a>
	</body>
</html>