django_project/urls.py
from django.contrib import admin
from django.urls import include, path       # Step 2.a import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls'))  # Step 2.b Create path to urls.py in the app
]

social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('guest-path', views.guest_path, name='guest-path'),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
    path("profile-page/<str:username>", views.profile_page, name="profile-page"),
    path("following/<str:username>", views.following_page, name="following"),

    # API Routes
    path("save-new-post", views.save_new_post, name="save-new-post"),
    path("save-edited-post/<int:postID>", views.save_edited_post, name="save-edited-post"),
    path("follow", views.follow, name="follow"),
    path("unfollow", views.unfollow, name="unfollow"),
    path("like-post/<int:postID>", views.like_post, name="like-post")
]

app_name = 'social'

workboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),						# normal path
	path('guest-path', views.guest_path, name='guest-path'),		# guest path
	path('guest-view', views.guest_view, name='guest-view'),

	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register_view, name='register'),

	# Index page paths
	path('create-board', views.create_board, name="create-board"),
	path('board-page/<int:board_id>', views.board_page, name="board-page"),

	# Board page paths
	path('columns/<int:board_id>', views.columns, name="columns"),
	path('col-options/<int:col_id>', views.col_options, name="col_options"),
	path('cards/<int:col_id>', views.cards, name="cards"),
	path('drag_and_drop', views.drag_and_drop, name="drag_and_drop")
]

app_name = 'workboard' # add this when using namespace in landing_page/urls.py

workboard/models.py
from django.db import models

# Import the following:
from landing_page.models import User

# Create your models here.

# Add a class for each board
class Board(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='boards')	# related name: User.maps
	title = models.CharField(max_length=50)
	description = models.TextField(blank=True)
	public_visibility = models.BooleanField(default=False)
	archived = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)

	def serialize(self):	# This function converts the response to JSON
		return {
			'id': self.id,
			'creator': self.creator,
			'title': self.title,
			'description': self.description,
			'public_visibility': self.public_visibility,
			'archived': self.archived,
			'timestamp': self.timestamp
		}


# Add a class for each column
class Column(models.Model):
	board = models.ForeignKey('Board', on_delete=models.CASCADE, related_name='columns')	# link each column to a board
	name = models.CharField(max_length=30)

	def serialize(self):
		return {
			'id': self.id,
			'board_title': self.board.title,
			'name': self.name,
			'board_archived': self.board.archived
		}


# Add a class for each card
class Card(models.Model):
	column = models.ForeignKey('Column', on_delete=models.CASCADE, related_name='cards')
	creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cards')
	text = models.TextField(blank=True, max_length=300)
	position = models.IntegerField(default=0)	# position in the column (used for delete and drag && drop)

	def serialize(self):
		return {
			'id': self.id,
			'column_id': self.column.id,
			'creator_username': self.creator.username,
			'text': self.text,
			'position': self.position
		}

workboard/views.py
from django.shortcuts import render

# Import the following:
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

import json

from landing_page.models import User
from .models import Board, Column, Card


# Create your views here.
def index(request):
	# Get all personal boards if user is logged in
	if request.user.is_authenticated:
		logged_user = User.objects.get(pk=request.user.id)
		personal_boards = Board.objects.filter(creator=logged_user, archived=False)
		archived_boards = Board.objects.filter(creator=logged_user, archived=True)
		return render(request, 'workboard/index.html', {
			'personal_boards': personal_boards,
			'archived_boards': archived_boards
		})
	else:	# Redirect to the login page
		return HttpResponseRedirect(reverse('login'))

#________________________________________________________GUEST
def guest_path(request):
	print("- workboard guest_view()")
	# Check if guest account already exists
	try:
		guest = User.objects.get(username='guest')
		print(" - Guest account exists")
	except User.DoesNotExist:
		print(" - Guest account does NOT exist")
		return HttpResponse("Guest account does not exist")
	login(request, guest)
	return HttpResponseRedirect(reverse('workboard:guest-view'))	# ensure we redirect to the index of workboard


def guest_view(request):
	if request.user.is_authenticated:
		logged_user = User.objects.get(pk=request.user.id)
		personal_boards = Board.objects.filter(creator=logged_user, archived=False)
		archived_boards = Board.objects.filter(creator=logged_user, archived=True)
		return render(request, 'workboard/index.html', {
			'personal_boards': personal_boards,
			'archived_boards': archived_boards
		})
	else:
		return HttpResponse("Could not show guest view")
#________________________________________________________BOARD
@login_required
def create_board(request):
	# Get the user Board inputs
	board_title = request.POST['board_title']
	board_description = request.POST['board_description']

	new_board = Board()
	new_board.creator = User.objects.get(pk=request.user.id)
	new_board.title = board_title
	new_board.description = board_description
	new_board.save()

	# Get the new board's id
	board_id = new_board.id

	# Redirect to the new board (passing board_id argument to reverse)
	return HttpResponseRedirect(reverse('workboard:board-page', kwargs={'board_id':board_id}))

@csrf_exempt
@login_required
def board_page(request, board_id):
	if request.method == "GET":
		return render(request, 'workboard/board-page.html', {
			'board_obj': Board.objects.get(pk=board_id)
		})
	elif request.method == "PUT":
		data = json.loads(request.body)

		if data['action'] == 'edit-title':
			new_title = data['new_title']

			board = Board.objects.get(pk=board_id)
			board.title = new_title
			board.save()

			return JsonResponse({'message': f"Board title updated: {new_title}"}, status=201)
		else:
			board = Board.objects.get(pk=board_id)
			board.archived = data['archive_board']	# will pass either True or False to archive
			board.save()
			return JsonResponse({'message': f"Board archived: {data['archive_board']}"}, status=201)
	else:
		return JsonResponse({'error': "GET OR PUT request required"}, status=400)

#________________________________________________________COLUMNS
@csrf_exempt
@login_required
def columns(request, board_id):
	if request.method == 'GET':
		columns = Column.objects.filter(board=Board.objects.get(pk=board_id))
		return JsonResponse([column.serialize() for column in columns], safe=False)

	elif request.method == 'POST':
		data = json.loads(request.body)
		new_column_name = data['column_name']
		column = Column()
		column.board = Board.objects.get(pk=board_id)
		column.name = new_column_name
		column.save()
		return JsonResponse(column.serialize(), safe=False)		# return the column that was saved

	else:
		return JsonResponse({'message': 'Arrived via PUT'}, status=201)

@csrf_exempt
@login_required
def col_options(request, col_id):
	if request.method == 'PUT':
		# Check if we edit or delete the column
		data = json.loads(request.body)
		action = data['action']
		column = Column.objects.get(pk=col_id)
		
		if (action == 'edit'):
			column.name = data['new_col_name']
			column.save()
			print(f"New column name : {data['new_col_name']}")
			return JsonResponse({'message': 'Column was edited successfully'}, status=201)
		elif (action == 'delete'):
			column.delete()
			return JsonResponse({'message': 'Column was deleted successfully.'}, status=201)
		else:
			return JsonResponse({'error': 'Cannot edit or delete column.'}, status=400)
	else:
		return JsonResponse({'error': 'GET or PUT request required.'}, status=400)

#________________________________________________________CARDS
@csrf_exempt
@login_required
def cards(request, col_id):
	if request.method == 'GET':		# get the cards from the database
		# Get the <QuerySet [<Card object>, <Card object>] in ascending order, ("-position") would be for descending
		cards_for_column = Card.objects.filter(column=Column.objects.get(pk=col_id)).order_by('position')
		return JsonResponse([card.serialize() for card in cards_for_column], safe=False) # Return an array of JASON data

	# save the card in the database
	elif request.method == 'POST': 		
		new_card_text = json.loads(request.body)['new_card_text']

		# get the number of cards in that column to know the positioning of the card
		column_parent = Column.objects.get(pk=col_id)
		cards_counter = Card.objects.filter(column=column_parent).count()
		
		new_card = Card()
		new_card.column = column_parent
		new_card.creator = User.objects.get(pk=request.user.id)
		new_card.text = new_card_text
		new_card.position = cards_counter	# position is the index of the card in the column (0 cards = position 0)
		new_card.save()
		return JsonResponse(new_card.serialize(), safe=False)

	# edit or delete card (we are passing the card_id)
	elif request.method == 'PUT':
		data = json.loads(request.body)
		action = data['action']
		card = Card.objects.get(pk=col_id)	# we are actually passing the card_id
		
		if (action == 'edit'):
			card.text = data['new_card_note']
			card.save()
			return JsonResponse({'message': 'Card edited successfully.'}, status=201)
		
		elif (action == 'delete'):	# Check the position of the card we are deleting
			column_parent = card.column
			cards_counter = Card.objects.filter(column=column_parent).count()

			if (card.position < cards_counter - 1):	 # e.g. col has 3 cards, last card's position is 2 (starts from 0)
				print(f" -- we are deleting NOT the last card")
				following_cards = Card.objects.filter(column=column_parent,position__gt=card.position)	# greater than
				for next_card in following_cards:	# change position of all following cards by - 1
					next_card.position -= 1
					next_card.save()
			else:
				print(" -- we are deleting the last card") # no change in cards position

			card.delete() # delete card in any case	
			return JsonResponse({'message': 'Card deleted successfully.'}, status=201)
		else:
			return JsonResponse({'error': 'Cannot edit or delete card'}, status=400)
	else:
		return JsonResponse({'error': "Cannot access cards"})

#________________________________________________________DRAG AND DROP
@csrf_exempt
def drag_and_drop(request):
	if request.method == 'PUT' and request.user.username != 'guest':
		print("User dropped a new card")
		data = json.loads(request.body)
		print(data)

		moved_card = Card.objects.get(pk=data['drag_card_id'])	# get the card we moved
		old_column = moved_card.column   						# get it's original column
		new_column = Column.objects.get(pk=data['new_col_id'])	# get the new column
		next_card = data['next_card_id']						# get the following card's id (-1 if no following card)

		old_position = moved_card.position
		last_pos_old_column = Card.objects.filter(column=old_column).count() - 1  # e.g. [a, b, (c)] - count=3 position=2 
		new_position = None

		if (next_card != -1):								# if there is a following card (NOT -1)
			next_card = Card.objects.get(pk=next_card)		# get that card
			new_position = next_card.position 				# get its position that will be later taken by the moved card

		print(f"moved card: {moved_card}")
		print(f"old column: {old_column}")
		print(f"new column: {new_column}")
		print(f"next card: {next_card}")


		# 1. Keeping card in the SAME column
		if (new_column == old_column):
			print("- SAME col")
			# 1.a. Card dropped in the SAME spot
			# 1.a.i. Card kept at the END of the list (also applies to list with one element)
			if (next_card == -1 and old_position == last_pos_old_column):
				print("-- SAME col STAYED END list") 
				return JsonResponse({'move': 
					f"SAME col STAYED END list -> {moved_card} | new col:{new_column}, new pos:{moved_card.position}"}, 
					status=201)
			
			# 1.a.ii. Card kept SAME SPOT (beginning or middle of the list with other cards)
			elif (next_card != -1 and old_position == new_position - 1):
				print("-- SAME col SAME spot")
				return JsonResponse({'move': 
					f"SAME col SAME spot -> {moved_card} | new col:{new_column}, new pos:{moved_card.position}"}, 
					status=201)
			
			# 1.b. Card dropped in DIFFERENT spot (still same column)
			# 1.b.i. Card dropped at the END of the list
			elif (next_card == -1):
				print("-- SAME col MOVED END list")
				following_cards = Card.objects.filter(column=old_column, position__gt=old_position)
				for card in following_cards:	# get all the following cards after the old position -> ]old_pos, ...]
					card.position -= 1 			# move their position up the list
					card.save()
				moved_card.position = last_pos_old_column # get the last position in the list
				moved_card.save()
				return JsonResponse({'move': 
					f"""SAME col MOVED END list -> {moved_card} | new col:{new_column}, new pos:{

workboard/templates/workboard/board-page.html
{% extends 'workboard/layout.html' %} {% load static %} {% block title %} -
Board Page{% endblock %} {% block body %}

<div id="board-container">
  <section id="board-header">
    <div class="inline-block">
      <h4 id="board-title" contenteditable="true">{{ board_obj.title}}</h4>
    </div>

    <!-- Add the archive buttons part of the title -->
    {% if board_obj.archived %}
    <!-- True means board is archived, make it unarchived -->
    <div class="inline-block">
      <button class="archive-btns btn btn-dark btn-sm" data-archived="False">
        Unarchive
      </button>
    </div>
    {% else %}
    <!-- Edit the board's title -->
    <div class="inline-block">
      <button
        id="edit-board-btn"
        class="btn btn-info btn-sm"
        data-boardid="{{board_obj.id}}"
      >
        Save Edit
      </button>
    </div>
    <div class="inline-block">
      <button
        class="archive-btns btn btn-secondary btn-sm"
        data-archived="True"
      >
        Archive
      </button>
    </div>
    {% endif %}
  </section>

  <section id="board-div">
    <div id="empty-board-msg">
      <h6>This board has no columns or cards.</h6>
      <button id="add-col-btn" class="add-col-form-btn btn btn-sm">
        Add a column
      </button>
    </div>

    <div id="cols-div"></div>

    <div>
      <button id="add-col-btn-lg" class="add-col-form-btn">+ Add column</button>
    </div>
  </section>
</div>

<div id="archived-layer"></div>

<!-- Modals -->
<div id="darken-overlay"></div>

<div id="add-col-modal">
  <h5 class="center-modal-title"><strong>Add a column</strong></h5>
  <button class="close-form-btn" onclick="close_form()">x</button>
  <hr />
  <form id="create-col-form" method="post">
    {% csrf_token %}
    <h6><strong>Column name</strong></h6>
    <input
      type="text"
      id="col-name-input"
      class="form-control form-input"
      autofocus
      placeholder="Enter a column name (To Do, In Progress, Done)"
      maxlength="15"
      required
    />
    <div class="center-btn">
      <input type="submit" class="btn btn-primary" value="Create column" />
    </div>
  </form>
</div>

<div id="edit-col-modal">
  <h5 class="center-modal-title"><strong id="edit-col-header"></strong></h5>
  <button class="close-form-btn" onclick="close_form()">x</button>
  <hr />
  <form id="edit-col-form" method="post">
    {% csrf_token %}
    <h6><strong>Column name</strong></h6>
    <input
      type="text"
      id="edit-col-name-input"
      class="form-control form-input"
      maxlength="15"
      required
    />
    <div class="center-btn">
      <input type="submit" class="btn btn-warning" value="Update column" />
    </div>
  </form>
</div>

<div id="edit-card-modal">
  <h5 class="center-modal-title"><strong>Edit card</strong></h5>
  <button class="close-form-btn" onclick="close_form()">x</button>
  <hr />
  <form id="edit-card-form" method="post">
    {% csrf_token %}
    <h6><strong>Card</strong></h6>
    <textarea
      id="edit-card-text-input"
      class="form-control h-25 form-input"
      maxlength="300"
      required
    ></textarea
    ><!-- h-25: max height of 25%-->
    <div class="center-btn">
      <input type="submit" class="btn btn-warning" value="Update card" />
    </div>
  </form>
</div>

{% endblock %} {% block script %}
<script src="{% static 'workboard/board-page.js' %}"></script>
{% endblock %}

workboard/templates/workboard/index.html
{% extends 'workboard/layout.html' %} {% load static %} {% block title %} - Home
{% endblock %} {% block body %} {% if user.is_authenticated %}
<div id="darken-overlay"></div>

<div id="create-board-modal">
  <h5 class="center-modal-title"><strong>Create a new board</strong></h5>
  <button class="close-form-btn">x</button>
  <hr />
  <!-- Create a new board, show the form only when button is clicked -->
  <form action="{% url 'workboard:create-board' %}" method="post">
    {% csrf_token %}

    <div class="form-input">
      <label><strong>Board title</strong></label>
      <input
        type="text"
        name="board_title"
        class="form-control"
        placeholder="Board title"
        maxlength="50"
        required
      />
    </div>

    <div class="form-input">
      <label><strong>Description</strong> (optional)</label>
      <textarea
        name="board_description"
        class="form-control"
        maxlength="300"
        rows="3"
      ></textarea>
    </div>

    <div class="center-btn">
      <input type="submit" class="btn btn-primary" value="Create Board" />
    </div>
  </form>
</div>

<div class="flex-container">
  <div class="flexbox-item">
    <div id="new-board-btn">
      <button id="create-board-form-btn">New Board</button>
    </div>

    <div id="more-boards">
      <h5>Your boards</h5>
      <ul class="boards-list">
        {% for board in personal_boards %}
        <!-- Adding a button inside the anchor tag -->
        <li>
          <a href="{% url 'workboard:board-page' board.id %}">
            <button class="active-list-item">
              {{ board.title }}<br /><span class="timestamp"
                >Created: {{ board.timestamp }}</span
              >
            </button>
          </a>
        </li>
        {% empty %}
        <li>You don't have any active boards.</li>
        {% endfor%}
      </ul>
      {% endif %}
      <!-- Show all archived boards -->
      {% if archived_boards %}
      <h5>Archived boards</h5>
      {% endif %}
      <ul class="boards-list">
        {% for board in archived_boards %}
        <li>
          <a href="{% url 'workboard:board-page' board.id %}">
            <button class="archived-list-item">
              {{ board.title }}<br /><span class="timestamp"
                >Created: {{ board.timestamp }}</span
              >
            </button>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

<script>
  !(function (d, s, id) {
    var js,
      fjs = d.getElementsByTagName(s)[0];
    if (!d.getElementById(id)) {
      js = d.createElement(s);
      js.id = id;
      js.src = "https://weatherwidget.io/js/widget.min.js";
      fjs.parentNode.insertBefore(js, fjs);
    }
  })(document, "script", "weatherwidget-io-js");
</script>
{% endblock %} {% block script %}
<script src="{% static 'workboard/index.js' %}"></script>
{% endblock %}

workboard/templates/workboard/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Workboard{% block title %}{% endblock %}</title>
		<link rel="icon" href="{% static 'landing_page/logos/cm-logo.png' %}">
		<!-- Add Bootstrap + CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'workboard/styles.css' %}">
		<!-- Add JavaScript -->
		{% block script %}
		{% endblock %}
	</head>
	<body>

		<nav class="navbar navbar-expand navbar-light"><!-- Format navbar using Bootstrap -->
			
			<span class="app-title"><strong>WorkBoard</strong></span>
			
			<ul class="navbar-nav ml-auto">	<!-- Remove bullet points and add spaces between the links -->
				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link"><strong>{{ user.username }}</strong></a>
					</li>

					<li class="nav-item">
						<a class="nav-link link-over" href="{% url 'workboard:guest-view' %}" title="View Projects">Home</a>
					</li>

					<li id="log-out" class="nav-item">
						<a class="nav-link link-over" href="{% url 'workboard:logout' %}" title="End session">Log Out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link link-over" href="{% url 'workboard:login' %}" title="Go to Login page">Log In</a>
					</li class="nav-item">
					<li class="nav-item">
						<a class="nav-link link-over" href="{% url 'workboard:register' %}" title="Go to Register page">Register</a>
					</li>
				{% endif %}
			</ul>
		
		</nav>

		{% block body %}
		{% endblock %}
	</body>
</html>

workboard/templates/workboard/login.html
{% extends 'workboard/layout.html' %} {% block title %} - Log In{% endblock %}
{% block body %}
<div class="flex-container">
  <div class="auth-form">
    <form action="{% url 'workboard:login' %}" method="post">
      {% csrf_token %}
      <input
        type="text"
        name="username"
        placeholder="Username"
        required
      /><br />
      <input
        type="password"
        name="password"
        placeholder="Password"
        required
      /><br />
      <input type="submit" value="Log In" class="btn btn-success" />
    </form>
    First time here?
    <a href="{% url 'workboard:register' %}">Create new account.</a>
  </div>
</div>
{% endblock %}

workboard/templates/workboard/register.html
{% extends 'workboard/layout.html' %}

{% block title %} - Register{% endblock %}

{% block body %}

    {% if message %}
        <div class="alert alert-primary" role="alert">{{ message }}</div>
    {% endif %}

	<div class="flex-container">
		<div class="auth-form">
			<!-- DISABLED REGISTER <form action="{% url 'workboard:register' %}" method="post"> -->
				<form>
				{% csrf_token %}
				<input type="text" autofocus name="username" placeholder="Username" required><br>
				<input type="text" name="email" placeholder="Email"><br>
				<input type="password" name="password" placeholder="Password" required><br>
				<input type="password" name="confirmation" placeholder="Confirm password" required><br>
				<input type="submit" value="Register" class="btn btn-primary">
			</form>
			Already have an account? <a href="{% url 'workboard:login' %}">Log In here.</a>
		</div>
	</div>
{% endblock %}