django_project/urls.py
from django.contrib import admin
from django.urls import include, path       # Step 2.a import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls'))  # Step 2.b Create path to urls.py in the app
]

e_commerce/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('guest-path', views.guest_path, name='guest-path'),
    
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("create-listing", views.create_listing, name="create-listing"),
    path("listing/<int:listing_id>", views.listing_page, name="listing"),
    path("listing-normal", views.listing_normal, name="listing-normal"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories-list", views.categories, name="categories-list"),
    path("category/<str:name>", views.category, name="category")
]

app_name = 'commerce'

social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('guest-path', views.guest_path, name='guest-path'),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
    path("profile-page/<str:username>", views.profile_page, name="profile-page"),
    path("following/<str:username>", views.following_page, name="following"),

    # API Routes
    path("save-new-post", views.save_new_post, name="save-new-post"),
    path("save-edited-post/<int:postID>", views.save_edited_post, name="save-edited-post"),
    path("follow", views.follow, name="follow"),
    path("unfollow", views.unfollow, name="unfollow"),
    path("like-post/<int:postID>", views.like_post, name="like-post")
]

app_name = 'social'

e_commerce/models.py
from django.db import models

from landing_page.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Listing(models.Model):
    title = models.CharField(max_length=30)
    starting_bid = models.DecimalField(max_digits=9, decimal_places=2) # Max number: 9,999,999.99
    current_bid = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    number_of_bids = models.IntegerField(default=0)

    description = models.CharField(max_length=280, blank=True)
    image_URL = models.CharField(max_length=6000, blank=True) # Will get an URL for the image (optionally)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name="list_category")

    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="list_seller")
    creation_date = models.CharField(max_length=40)
    
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title} ${self.starting_bid} ${self.current_bid} '{self.description}' {self.seller}"


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bid")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_bid")
    bid_amount = models.DecimalField(max_digits=9, decimal_places=2)        # The largest number will tell us the highest bidder

    def __str__(self):
        return f"{self.user.username} - {self.listing.title} - ${self.bid_amount}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_comments")
    comment = models.CharField(max_length=280, blank=True)
    date = models.CharField(max_length=40)
    
    def __str__(self):
        return f"User: {self.user.username} - Listing: {self.listing.title} - Comment: {self.comment}"


class Watchlist(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name="user_watchlist")  
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_watchlist")                      
    
    def __str__(self):
        return f"UserID: {self.user}, ListingID: {self.listing.title}"


"""
Order the classed based on how they reference the foreign key.
Every time we change something in models.py we need to:
$ python3 manage.py makemigrations auctions
$ python3 manage.py migrate
"""

e_commerce/views.py
from django.contrib.auth import authenticate, login, logout, decorators
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from landing_page.models import User
from .models import Listing, Bid, Comment, Watchlist, Category
from datetime import datetime   # Used to get current time
from pytz import timezone       # Used to transform timezones
from django import forms        # Used to create Django forms

#_____________________________________Home Page_____________________________________
def index(request):
    """
    This is the active listing page.
    """
    listings = Listing.objects.order_by('-creation_date').all()
    try:    # Run this if we have an userId (created after user logged in)
        print(f"Index userID: {request.session['userID']}")
        return render(request, "commerce/index.html", {
            "listings": listings,
            "currentUserWins": getUserListingWins(request)
        })
    except KeyError:        # Show this if we got to the page without a user id
        return render(request, "commerce/index.html", {
            "listings": listings
        })

def guest_path(request):
    # Check if guest account already exists
    try:
        guest = User.objects.get(username='guest')
    except User.DoesNotExist:
        return HttpResponse("Guest account does not exist")
    login(request, guest)
    request.session["userID"] = guest.id              # Save the user's id in the session
    return HttpResponseRedirect(reverse('commerce:index'))    # ensure we redirect to the index of workboard

def getUserListingWins(request):
    """
    Get all the listing the current user won.
    """
    currentUser = request.session['userID']
    listings = Listing.objects.all()
    closedListings = Listing.objects.filter(active=False) # Get all the closed listings
    currentUserWins = []    # Store all the closed listings where the current user is the winner

    for listing in closedListings:                   # Parse thorough all the closed listings   
        if getHighestBid(listing):                   # Some listings might be closed with no bids (Returns None)
            highestBidder = getHighestBid(listing).user.id  # Get the user id of the highest bidder)
            if currentUser == highestBidder:             # Check if the current user is the highest bidder   
                currentUserWins.append(listing)          # Add the winning listing to the list

    return currentUserWins


class ListingForm(forms.Form):
    title = forms.CharField(
                    label="",   # Need empty label even when using placeholder
                    widget=forms.TextInput(attrs={'placeholder': 'Title'}),
                    max_length=30)
    description = forms.CharField(
                    label="",
                    widget=forms.Textarea(attrs={'placeholder': 'Description (Optional)'}), 
                    max_length=280, 
                    required=False)
    starting_bid = forms.DecimalField(
                    label="",
                    widget=forms.NumberInput(attrs={'placeholder': 'Starting Bid'}), 
                    min_value=0, 
                    max_digits=9,
                    max_value=9999999, 
                    decimal_places=2)
    image_URL = forms.CharField(    # Same as in the model
                    label="", 
                    max_length=6000,
                    widget=forms.TextInput(attrs={'placeholder': 'Image URL (Optional)'}), 
                    required=False)   
    category = forms.ModelChoiceField(
                    label='Category (Optional)',
                    queryset=Category.objects.order_by('name').all(),
                    required=False)


#_____________________________________Create Listing_____________________________________
def create_listing(request):
    """
    This lets the user create a new listing by getting the input from the form, Django does 
    the error checking and then store it in the database.
    """
    categories = Category.objects.order_by('name').all() 

    if request.method == "POST":
        # Take the user's data submitted and save it as a form
        form = ListingForm(request.POST)   # request.POST contains the data the user submitted into the form 

        if form.is_valid():
            # Get the inputs from the form field
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            starting_bid = form.cleaned_data["starting_bid"]
            image_URL = form.cleaned_data["image_URL"]
            category = form.cleaned_data["category"]

            # Store them in the database
            listing = Listing()
            listing.title = title
            listing.description = description
            listing.starting_bid = starting_bid
            listing.image_URL = image_URL
            
            if category:    # Check if user provided a category before accessing the Category model
                listing.category = Category.objects.get(name=category)
            
            listing.seller = User.objects.get(pk=request.session["userID"])
            listing.creation_date = currentTime()
            listing.save()

        else: # Render the page back with the user's form if form is not valid
            return render(request, "commerce/create-listing.html", {
                "categories": categories,
                "create_listing_form": form,     # Send the form back to the user to see their inputs
                "create_listing_form": ListingForm()
            })

        # Redirect to the created listing by passing the argument list's id as a tuple
        return HttpResponseRedirect(reverse("commerce:listing", args=(listing.id,)))

    # Method was GET
    else:
        return render(request, "commerce/create-listing.html", {
            "categories": categories,
            "create_listing_form": ListingForm()
        })       
    

#_____________________________________Listing Page_____________________________________
@login_required(login_url='listing-normal')    # redirect when user is not logged in (check settings)
def listing_page(request, listing_id): 
    """
    This displays the listing's page the user clicked on or was redirected to.
    """
  
    # Check if the user already has the item saved in the watchlist
    currentUser = User.objects.get(pk=request.session["userID"]) # Get the current user object
    userWatchlist = currentUser.user_watchlist.all()  # Get all current user's items using related name 

    watchlist_btn = "add_watchlist"
    inWatchlist = False
    error = ""
    success = ""

    # Get the current listing object befor the post method is requested
    currentListing = Listing.objects.get(pk=listing_id)
    highestBid = getHighestBid(currentListing)  # Get the highest bid for the current listing

    comments = currentListing.listing_comments.all()

    for item in userWatchlist:
        if item.listing.id == listing_id:
            inWatchlist = True
            watchlist_btn = "remove_watchlist"
            instance = Watchlist.objects.filter(    # Create an instance if user wants to remove the item later
                            user=currentUser
                        ).filter(
                            listing=currentListing  
                        )
        
    # Let user add the item to their "Watchlist", if already added, the user should be able to remove it
    
    if request.method == "POST":

        # Add or remove item from watchlist (based on button name)
        if request.POST.get("add_watchlist"):               # Check if "add_watchlist" button was pressed
            addToWatchlist(currentUser, currentListing)     # Add current listing to watchlist
            return HttpResponseRedirect(reverse("commerce:listing", args=(listing_id,)))
        
        elif request.POST.get("remove_watchlist"):          # Watchlist btn is set to remove
            instance.delete()                               # Delete the item from the watchlist model.
            return HttpResponseRedirect(reverse("commerce:listing", args=(listing_id,)))

        # User wants to bid 
        elif request.POST.get("place_bid_btn"):                  # Check if place bid button was pressed
            if not request.POST["bid_amount"]:                   # Check if bid value is empty
                error = "No bid was entered"
            else:
                new_bid = float(request.POST["bid_amount"])      # Cast string input to a float

                # Bid must be as large as the starting bid or greater than any other bids
                if currentListing.current_bid == 0 and new_bid < currentListing.starting_bid: # Check for first bid
                    error = f"Bid of ${new_bid} is lower than the starting bid"
                elif new_bid <= currentListing.current_bid:
                    error = f"Bid of ${new_bid} is not higher than the current bid"
                else:                                  # Add the new bid and return the highest bid before rendering   
                    highestBid = addNewBid(new_bid, currentListing, currentUser)
                    success = "You are the highest bidder" 
                    
            return render(request, "commerce/listing.html", {
                "currentUser": currentUser,
                "listing": currentListing,
                "inWatchlist": inWatchlist,
                "watchlist_btn": watchlist_btn,
                "highestBid": highestBid,
                "comments": comments,
                "error": error,
                "success": success,
            })
        
        # Closing the listing (and make the highest bidder the winner)
        elif request.POST.get("close_listing_btn"):                 # Check if close listing button was pressed

e_commerce/templates/commerce/categories-list.html
{% extends "commerce/layout.html" %}

{% block title %} - Categories {% endblock %}

{% block body %}
	<h3>List of categories:</h3>
	<!-- Add the code below this -->
	{% for category in categories %}
		<ul>
			<!-- The category should pass something -->
			<li><a href="{% url 'commerce:category' category.name %}">{{ category }}</a></li>
		</ul>
	{% empty %}
		<p>There are no categories created yet.</p>
	{% endfor %}

{% endblock %}

e_commerce/templates/commerce/create-listing.html
{% extends "commerce/layout.html" %}

{% block title %} - New Listing {% endblock %}

{% block body %}

	<h2>Create a new listing:</h2>
	<form action="{% url 'commerce:create-listing' %}" method="post">
		{% csrf_token %}
		{{ create_listing_form.as_p }}
		<input type="submit" value="Post Listing">
	</form>
		
{% endblock %}

e_commerce/templates/commerce/index.html
{% extends "commerce/layout.html" %}
{% load humanize %}<!-- Format large numbers with comma 1/3 (add the app in settings.py for 3/3)-->

{% block title %}{% endblock %}

{% block body %}
    {% if page == "category" %}
        <h2>Listings in {{ category }}</h2>
    {% else %}
        
        {% if currentUserWins %}    <!-- Check if the current user has some closed listings they won -->
            <h3>You won the following listings!</h3>
            {% for wonListing in currentUserWins %}
                <ul>
                    <li>
                        <b><a href="{% url 'commerce:listing' wonListing.id %}" style="text-decoration:none;">
                    {{ wonListing.title }} closed at ${{ wonListing.current_bid }}</a></b>
                    </li>
                </ul>
            {% endfor %}
        {% endif %}
        
        <h2>Active Listings</h2>
    
    {% endif %}

    <!-- Display all active listings -->
    <table style="width: 100%;">

        {% for listing in listings %}
            
            {% if listing.active %}
                <tr style="border: 1px solid lightgrey;">
                    <td style="width:30%; text-align: center">  <!-- Align images in the middle -->
                        {% if listing.image_URL %} <!-- Show image if it was provided -->
                            <img src="{{ listing.image_URL}}" alt="{{ listing.title }}" width="200">
                        {% else %}
                            <img src="../static/commerce/No_image_available.png" alt="No image" width="200">
                        {% endif %}
                    </td>
                    <td>
                        <p><b><a href="{% url 'commerce:listing' listing.id %}" style="text-decoration:none;">
                            {{ listing.title }}
                        </a></b></p>

                        <!-- Check if we display the starting or current bid -->
                        {% if listing.current_bid == 0 %}
                            <p><b>Price:</b> ${{ listing.starting_bid|intcomma }}</p><!-- Format large numbers with comma 2/3-->
                        {% else %}
                            <p><b>Price:</b> ${{ listing.current_bid|intcomma }}</p><!-- Format large numbers with comma 2/3-->
                        {% endif %}
                        
                        {% if listing.description %}
                            <p>{{ listing.description }}</p>
                        {% endif %}
                        
                        <p>Seller: {{ listing.seller.username }} <span style="font-size: 80%;color: grey;"> - Created: {{ listing.creation_date }}</span></p>
                    </td>
                </tr>
                
            {% endif %}
        {% empty %} <!-- Show this message if there are no active listings -->
                    <p>There are no active listings</p>
        {% endfor %}
    </table>

{% endblock %}

e_commerce/templates/commerce/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charste="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>E-Commerce{% block title %}{% endblock %}</title>
        <link rel="icon" href="{% static 'landing_page/logos/cm-logo.png' %}">
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'commerce/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'commerce:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'commerce:categories-list' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <!-- Add nb indicating number of items in list -->
                    <a class="nav-link" href="{% url 'commerce:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:create-listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

e_commerce/templates/commerce/listing-normal.html
<!-- Similar to listing.html, but it does not have the forms -->
{% extends "commerce/layout.html" %} 
{% load humanize %}

{% block title %} - Listing: {{listing.title }} {% endblock %}

{% block body %}
	<h2>Listing: {{ listing.title }}{% if not listing.active %} (CLOSED){% endif %}</h2> 
    <br>
	
    {% if listing.image_URL %} <!-- Show image if it was provided -->
    	<img src="{{ listing.image_URL}}" alt="{{ listing.title }}" width="200">
    {% else %}
    	<img src="../static/commerce/No_image_available.png" alt="No image" width="200">
    {% endif %}

    {% if listing.description %}
    	<p>{{ listing.description }}</p>
    {% endif %}

    <!-- Check if we display the starting or current bid -->
    {% if listing.current_bid == 0 %}
        <h2>${{ listing.starting_bid|intcomma }}</h2><!-- Format large numbers with comma 2/3-->
    {% else %}
        <h2>${{ listing.current_bid|intcomma }}</h2><!-- Format large numbers with comma 2/3-->
    {% endif %}
    

    <p>
        {{ listing.number_of_bids }} bid(s) so far.
        {% if listing.number_of_bids == 0 %}
            Start bidding.
        {% else %}
            <b>{{ highestBid.user.username }}</b> has the highest bid
        {% endif %}
    </p>

    <h3>Details</h3>
    <ul>
    	<li>Listed by: {{ listing.seller.username }}</li>
        {% if listing.category %}
    	   <li>Category: {{ listing.category }}</li>
        {% endif %}
    </ul>

    <hr>
    <h3>Comments Section</h3>
    <h4 style="margin:10px 0px">Other comments:</h4>

    {% for comment in comments %}
        <div style="boder:1px solid lightgrey;">
            <h6>{{ comment.user.username }} <span style="font-size: 80%;color: grey;">- {{ comment.date }}</span></h6>
            <p>{{ comment.comment }}</p>
        </div>
    {% empty %}
        <p>Comment section is empty.</p>
    {% endfor %}

{% endblock %}

e_commerce/templates/commerce/listing.html
{% extends "commerce/layout.html" %} {% load humanize %}<!-- Format large numbers with comma 1/3 (settings.py for 3/3)-->

{% block title %} - Listing: {{listing.title }} {% endblock %} {% block body %}
<h2>
  Listing: {{ listing.title }}{% if not listing.active %} (CLOSED){% endif %}
</h2>

{% if listing.seller.username == currentUser.username %}
<p>You are the owner of this listing</p>

{% else %} {% if listing.active %}
<form action="{% url 'commerce:listing' listing.id %}" method="post">
  {% csrf_token %} {% if inWatchlist %}
  <input
    type="submit"
    name="{{ watchlist_btn }}"
    value="- Watchlist"
    class="btn btn-secondary"
    style="font-size: 12px; padding: 2px"
    title="Remove from watchlist"
  />
  {% else %}
  <input
    type="submit"
    name="{{ watchlist_btn }}"
    value="+ Watchlist"
    class="btn btn-primary"
    style="font-size: 12px; padding: 2px"
    title="Add to watchlist"
  />
  {% endif %}
</form>
{% endif %} {% endif %}
<br />

{% if listing.image_URL %}
<img src="{{ listing.image_URL}}" alt="{{ listing.title }}" width="200" />
{% else %}
<img
  src="../static/commerce/No_image_available.png"
  alt="No image"
  width="200"
/>
{% endif %} {% if listing.description %}
<p>{{ listing.description }}</p>
{% endif %} {% if listing.current_bid == 0 %}
<h2>${{ listing.starting_bid|intcomma }}</h2>
<!-- Format large numbers with comma 2/3-->
{% else %}
<h2>${{ listing.current_bid|intcomma }}</h2>
<!-- Format large numbers with comma 2/3-->
{% endif %}

<p>
  {{ listing.number_of_bids }} bid(s) so far. {% if highestBid.user.username ==
  currentUser.username and not listing.active %} Congratulations! You won this
  bid! {% elif highestBid.user.username == currentUser.username %} Your bid is
  the current bid. {% elif listing.number_of_bids == 0 %} Start bidding. {% else
  %}
  <b>{{ highestBid.user.username }}</b> has the highest bid {% endif %}
</p>

{% if listing.active %} {% if listing.seller.username == currentUser.username %}
<form action="{% url 'commerce:listing' listing.id %}" method="post">
  {% csrf_token %}
  <input type="submit" name="close_listing_btn" value="Close Listing" />
</form>

{% else %}

<form action="{% url 'commerce:listing' listing.id %}" method="post">
  {% csrf_token %}
  <!-- Will not accept bids with decimals -->
  <input
    type="number"
    name="bid_amount"
    min="0"
    step=".01"
  /><!-- Allow 2 decimal places with step -->
  {% if error %}
  <span style="color: red">{{ error }}</span>
  {% else %}
  <span style="color: green">{{ success }}</span>
  {% endif %}
  <br />
  <input
    type="submit"
    name="place_bid_btn"
    value="Place Bid"
    class="btn btn-primary"
    style="margin: 10px 0px 20px 0px"
    title="Bid must be equal to starting bid or greater than existing bids"
  />
</form>

{% endif %} {% endif %}
<h3>Details</h3>
<ul>
  <li>Listed by: {{ listing.seller.username }}</li>
  {% if listing.category %}
  <li>Category: {{ listing.category }}</li>
  {% endif %}
</ul>

<hr />
<h3>Comments Section</h3>
{% if listing.active %}
<form
  action="{% url 'commerce:listing' listing.id %}"
  method="post"
  id="inputComment"
>
  {% csrf_token %}
  <textarea name="comment" maxlength="280" rows="4" cols="50"></textarea><br />
  <input type="submit" name="comment_btn" value="Post Comment" />
</form>
{% else %}
<form>
  {% csrf_token %}
  <textarea
    placeholder="Comment section is closed"
    rows="4"
    cols="50"
    disabled
  ></textarea
  ><br />
  <input type="submit" value="Post Comment" disabled />
</form>
{% endif %}

<h4 style="margin: 10px 0px">Other comments:</h4>

{% for comment in comments %}
<div style="boder: 1px solid lightgrey">
  <h6>
    {{ comment.user.username }}
    <span style="font-size: 80%; color: grey">- {{ comment.date }}</span>
  </h6>
  <p>{{ comment.comment }}</p>
</div>
{% empty %}
<p>Comment section is empty.</p>
{% endfor %} {% endblock %}

e_commerce/templates/commerce/login.html
{% extends "commerce/layout.html" %}

{% block title %} - Login {% endblock %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'commerce:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'commerce:register' %}">Register here.</a>

{% endblock %}

e_commerce/templates/commerce/register.html
{% extends "commerce/layout.html" %}

{% block title %} - Register {% endblock %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <!-- DISABLED REGISTER <form action="{% url 'commerce:register' %}" method="post"> -->
        <form>
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'commerce:login' %}">Log In here.</a>

{% endblock %}

e_commerce/templates/commerce/watchlist.html
{% extends "commerce/layout.html" %}
{% load humanize %}

{% block title %} - Watchlist {% endblock %}

{% block body %}
    <h2>Your saved items:</h2>

    <table style="width: 100%;">

        {% for item in watchlist %}
        
            <tr style="border: 1px solid lightgrey;">
                <td style="width:30%; text-align: center">  <!-- Align images in the middle -->
                    {% if item.listing.image_URL %} <!-- Show image if it was provided -->
                        <img src="{{ item.listing.image_URL}}" alt="{{ item.listing.title }}" width="200">
                    {% else %}
                        <img src="static/commerce/No_image_available.png" alt="No image" width="200">
                    {% endif %}
                </td>
                <td>
                    <p><b><a href="{% url 'commerce:listing' item.listing.id %}" style="text-decoration:none;">
                        {{ item.listing.title }}{% if not item.listing.active %} (CLOSED){% endif %}
                    </a></b></p>

                    <!-- Check if we display the starting or current bid -->
                    {% if item.listing.current_bid == 0 %}
                        <p><b>Price:</b> ${{ item.listing.starting_bid|intcomma }}</p><!-- Format large numbers with comma 2/3-->
                    {% else %}
                        <p><b>Price:</b> ${{ item.listing.current_bid|intcomma }}</p><!-- Format large numbers with comma 2/3-->
                    {% endif %}
                    
                    {% if item.listing.description %}
                        <p>{{ item.listing.description }}</p>
                    {% endif %}
                    <p>Seller: {{ item.listing.seller.username }}</p>
                    {% if item.listing.category %}
                        <p>Category: {{ item.listing.category }}</p>
                    {% endif %}
                </td>
            </tr>
            
            {% empty %} <!-- Show this message if there are no active listings -->
                <p>There are no saved items in your watchlist.</p>
        
        {% endfor %}
    </table>
{% endblock %}