django_project/urls.py
from django.contrib import admin
from django.urls import include, path       # Step 2.a import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls'))  # Step 2.b Create path to urls.py in the app
]

social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('guest-path', views.guest_path, name='guest-path'),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
    path("profile-page/<str:username>", views.profile_page, name="profile-page"),
    path("following/<str:username>", views.following_page, name="following"),

    # API Routes
    path("save-new-post", views.save_new_post, name="save-new-post"),
    path("save-edited-post/<int:postID>", views.save_edited_post, name="save-edited-post"),
    path("follow", views.follow, name="follow"),
    path("unfollow", views.unfollow, name="unfollow"),
    path("like-post/<int:postID>", views.like_post, name="like-post")
]

app_name = 'social'

social/models.py
from django.db import models

from landing_page.models import User

# Create your models here.
class Post(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    post = models.CharField(max_length=280)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def serialize(self):
        return {
            'id': self.id,
            'creator': self.creator.username,
            'post': self.post,
            'timestamp': self.timestamp.strftime("%b %d %Y, %I:%M %p"),
            'likes': self.likes
        }


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_likes')
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='post_likes')


class Follower(models.Model):
    # the logged user
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')     
    # the other user
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')

social/views.py
import json

from django.core.paginator import Paginator     # Used to show 10 posts per page
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required   # Used for #login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse # Used JR for returning error/success
from django.shortcuts import render
from django.urls import reverse

from landing_page.models import User
from .models import Post, Like, Follower

from django.views.decorators.csrf import csrf_exempt   # Will try to implement csrf later

from datetime import datetime


def index(request):
    """ This renders the All Posts page """
    allPosts = Post.objects.order_by('-timestamp').all()

    # Adding the paginator - source: https://docs.djangoproject.com/en/3.0/topics/pagination/
    paginator = Paginator(allPosts, 10) # Show 10 posts per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, "social/index.html", {
        # Return posts in reverse chronological order
        "allPosts": page_obj,
        "displayPagination": areMoreThanTenItems(allPosts)
    })

#________________________________________________________GUEST
def guest_path(request):
    # Check if guest account already exists
    try:
        guest = User.objects.get(username='guest')
    except User.DoesNotExist:
        return HttpResponse("Guest account does not exist")
    login(request, guest)
    return HttpResponseRedirect(reverse('social:index'))    # ensure we redirect to the index of workboard


def profile_page(request, username):
    """ This renders the user's profile page """
    userObject = User.objects.get(username=username)    # This is the user from where the page was linked

    userPosts = Post.objects.filter(creator=userObject).order_by('-timestamp')
    paginator = Paginator(userPosts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Check if viewing a profile page not from a logged user
    if not request.user.id:     # request.user.id would return None if no user is logged in
        return render(request, "social/default-profile.html", {
            "userProfileObject": userObject,
            "userPosts": page_obj,
            "displayPagination": areMoreThanTenItems(userPosts)
        })    
    else:
        return render(request, "social/profile.html", {
            "loggedUser": request.user,
            "userProfileObject": userObject,
            "isFollowing": isFollowing(request.user.id, userObject.id),
            "userPosts": page_obj,
            "displayPagination": areMoreThanTenItems(userPosts)
        })

def isFollowing(loggedUserID, otherUserID):
    """ Check if the logged user is following the other user """
    loggedUser = User.objects.get(pk=loggedUserID)
    otherUser = User.objects.get(pk=otherUserID)
    # Return True if there is one object where the logged user is following the other user
    return Follower.objects.filter(user=loggedUser, following=otherUser).exists()

#________________________________________________________ Follow
@csrf_exempt
@login_required
def follow(request):
    return_error_if_method_not_POST(request)

    data = json.loads(request.body)
    newFollowing = data.get("newFollowing", "")

    loggedUserObject = User.objects.get(pk=request.user.id)
    otherUserObject = User.objects.get(username=newFollowing)
    # Add the new profile to the following list of the logged user
    followerModel = Follower()
    followerModel.user = loggedUserObject
    followerModel.following = otherUserObject
    followerModel.save()

    # Increment the number of followings for the logged user and the other user
    loggedUserObject.number_of_followings += 1
    loggedUserObject.save()
    otherUserObject.number_of_followers += 1
    otherUserObject.save()
    return JsonResponse({"message": "New user is followed"}, status=201)

#________________________________________________________ Unfollow
@csrf_exempt
@login_required
def unfollow(request):
    return_error_if_method_not_POST(request)

    removeFollowing = json.loads(request.body).get("removeFollowing", "")
    loggedUserObject = User.objects.get(pk=request.user.id)
    otherUserObject = User.objects.get(username=removeFollowing)

    # Delete the following link from the models
    Follower.objects.get(user=loggedUserObject, following=otherUserObject).delete()
    # Decrement the number of followers for the logged and other user
    loggedUserObject.number_of_followings -= 1
    loggedUserObject.save()
    otherUserObject.number_of_followers -= 1
    otherUserObject.save()

    return JsonResponse({"message": "User is unfollowed"}, status=201)
   

#________________________________________________________ Following page
@login_required
def following_page(request, username):
    """ This renders the page with all posts made by users that the current user follows """
    return_error_if_method_not_POST(request)

    # Get all the objects from the Follower model
    followerObjects = Follower.objects.filter(user=User.objects.get(username=username))

    # Get all the users we are following in a list
    users_we_follow = []
    for user in followerObjects:
        users_we_follow.append(user.following)

    # Get all the posts of the users we are following (many-to-many) in reverse chronological order
    users_we_follow_posts = Post.objects.filter(creator__in=users_we_follow).order_by('-timestamp')
    
    # Adding the paginator
    paginator = Paginator(users_we_follow_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "social/following.html", {
        "users_we_follow_posts": page_obj,
        "displayPagination": areMoreThanTenItems(users_we_follow_posts)
    })


#________________________________________________________ Create new post
@csrf_exempt
@login_required
def save_new_post(request):

    # Creating a new post must be via POST
    return_error_if_method_not_POST(request)

    # Get post data
    data = json.loads(request.body)
    newPost = data.get("newPost", "")  # check if this is empty

    if not newPost:
        return JsonResponse({"error": "Cannot create an empty post"}, status=400)

    # Store the post in the database
    postModel = Post()
    postModel.creator = User.objects.get(pk=request.user.id)
    postModel.post = newPost
    postModel.save()

    return JsonResponse({"message": "Post created successfully."}, status=201)

#________________________________________________________ Edit post
@csrf_exempt
@login_required
def save_edited_post(request, postID):
    return_error_if_method_not_POST(request)

    editedPost = json.loads(request.body).get("editedPost", "")

    existingPost = Post.objects.get(pk=postID)      # Update the existing post
    existingPost.post = editedPost
    existingPost.timestamp = datetime.now()         # Update the timestamp
    existingPost.save()

    return JsonResponse({"message": "Post edited successfully."}, status=201)


#________________________________________________________ Like/Unlike post
@csrf_exempt
@login_required
def like_post(request, postID):

    loggedUser = User.objects.get(pk=request.user.id)
    postObject = Post.objects.get(pk=postID)

    # Check if post is already liked by the logged user
    likedPost = Like.objects.filter(user=loggedUser, post=postObject)
    if (likedPost.exists()):
        # Remove the like
        likedPost.delete()      # Remove the like (row for user and post)
        postObject.likes -= 1   # Decrement the number of likes
        postObject.save()
    else:
        newLike = Like()
        newLike.user = loggedUser
        newLike.post = postObject
        newLike.save()
        postObject.likes += 1
        postObject.save()
    
    likes = Post.objects.get(pk=postID).likes
    # Return the number of likes
    return JsonResponse(likes, safe=False)


#________________________________________________________ Login
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            
            return HttpResponseRedirect(reverse("social:index"))
        else:
            return render(request, "social/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "social/login.html")

#________________________________________________________ Logout
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("social:index"))

#________________________________________________________ Register
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "social/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "social/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("social:index"))
    else:
        return render(request, "social/register.html")

social/templates/social/default-profile.html
<!-- This is the profile page of each user when NOT logged in -->
{% extends "social/layout.html" %} {% load static %} {% block title %} - Profile
{% endblock %} {% block body %}
<table id="profile-page-header">
  <tr>
    <td><h3>{{ userProfileObject.username }}'s profile</h3></td>
    <td></td>
  </tr>
  <tr>
    <td>
      <table id="follow-table">
        <tr>
          <td class="follow-data">
            <b>{{ userProfileObject.number_of_followers }}</b>
          </td>
          <td class="follow-data">
            <b>{{ userProfileObject.number_of_followings }}</b>
          </td>
        </tr>
        <tr>
          <td class="follow-data">followers</td>
          <td class="follow-data">following</td>
        </tr>
      </table>
    </td>
    <td></td>
  </tr>
</table>

{% for post in userPosts%}
<div class="div-border">
  <p><b>{{ post.creator.username }}</b></p>
  <!-- Show the edit button if the profile's page belongs to the logged user -->
  {% if loggedUser.username == userProfileObject.username %}
  <button data-postid="{{post.id}}" class="edit-btn">Edit</button>
  {% endif %}
  <div id="postID-{{post.id}}">{{ post.post }}</div>
  <div class="ligthgray-text">{{ post.timestamp }}</div>
  <div>
    {% if user.is_authenticated %}
    <button data-postid="{{post.id}}" class="like-btn">
      <img
        src="{% static 'social/like-logo.png' %}"
        alt="Like logo"
        width="20"
      />
    </button>
    <span id="likesID-{{post.id}}" class="ligthgray-text"
      >{{ post.likes }}</span
    >
    {% else %}
    <img src="{% static 'social/like-logo.png' %}" alt="Like logo" width="20" />
    <span id="likesID-{{post.id}}" class="ligthgray-text"
      >{{ post.likes }}</span
    >
    {% endif %}
  </div>
</div>
{% endfor %} {% if displayPagination %}
<!-- Source: https://docs.djangoproject.com/en/3.0/topics/pagination/ -->
<nav aria-label="Page navigation between posts">
  <!-- Aligning the pagination components in the middle with flexbox -->
  <ul class="pagination justify-content-center">
    {% if userPosts.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ userPosts.previous_page_number }}"
        >&laquo;</a
      >
    </li>
    {% endif %}

    <li class="page-item">
      <a class="page-link" href="#">{{ userPosts.number }}</a>
    </li>

    {% if userPosts.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ userPosts.next_page_number }}"
        >&raquo;</a
      >
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ userPosts.paginator.num_pages }}"
        >last</a
      >
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} {% endblock %} {% block script %}
<script src="{% static 'social/social.js' %}"></script>
{% endblock %}

social/templates/social/following.html
{% extends "social/layout.html" %} {% load static %} {% block title %} -
Following {% endblock %} {% block body %}
<div id="following-posts">
  <h3>People you follow</h3>

  {% for post in users_we_follow_posts %}
  <div class="div-border">
    <p>
      <a href="{% url 'social:profile-page' post.creator.username %}">
        <b>{{ post.creator.username }}</b>
      </a>
    </p>
    <div>{{ post.post }}</div>
    <div class="ligthgray-text">{{ post.timestamp }}</div>
    <div>
      <button data-postid="{{post.id}}" class="like-btn">
        <img
          src="{% static 'social/like-logo.png' %}"
          alt="Like logo"
          width="20"
        />
      </button>
      <span id="likesID-{{post.id}}" class="ligthgray-text"
        >{{ post.likes }}</span
      >
    </div>
  </div>
  {% empty %}
  <p>You are not following anyone.</p>
  {% endfor %} {% if displayPagination %}
  <nav aria-label="Page navigation between posts">
    <!-- Aligning the pagination components in the middle with flexbox -->
    <ul class="pagination justify-content-center">
      {% if users_we_follow_posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ users_we_follow_posts.previous_page_number }}"
          >&laquo;</a
        >
      </li>
      {% endif %}

      <li class="page-item">
        <a class="page-link" href="#">{{ users_we_follow_posts.number }}</a>
      </li>

      {% if users_we_follow_posts.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ users_we_follow_posts.next_page_number }}"
          >&raquo;</a
        >
      </li>
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ users_we_follow_posts.paginator.num_pages }}"
          >last</a
        >
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

{% endblock %} {% block script %}
<script src="{% static 'social/social.js' %}"></script>
{% endblock %}

social/templates/social/index.html
{% extends "social/layout.html" %} {% load static %} {% block body %}
<section id="all-posts-view">
  <h2>All Posts</h2>

  {% if user.is_authenticated %}
  <div id="new-post-view" class="new-post-container">
    <form id="new-post-form">
      <!--{% csrf_token %} WILL IMPLEMENT THIS LATER exempt for now-->
      <textarea
        id="new-post"
        class="form-control"
        placeholder="What's on your mind?"
        maxlength="280"
      ></textarea>
      <input type="submit" value="Post" />
    </form>
  </div>
  {% endif %} {% for post in allPosts %}
  <div class="div-border">
    <div class="post-header">
      <a href="{% url 'social:profile-page' post.creator.username %}">
        <strong>{{ post.creator.username }}</strong>
      </a>
      <span class="ligthgray-text">{{ post.timestamp }}</span>
    </div>

    <!-- This displays the actual post -->
    <div id="postID-{{post.id}}" class="post-container">{{ post.post }}</div>

    <div class="post-buttons">
      {% if user.is_authenticated %}
      <div class="buttons-and-data">
        <button data-postid="{{post.id}}" class="like-btn">
          <img
            src="{% static 'social/icons/like_icon.svg' %}"
            alt="Like icon"
            width="20"
          />
        </button>
        <span id="likesID-{{post.id}}" class="ligthgray-text"
          >{{ post.likes }}</span
        >
      </div>

      <div class="buttons-and-data">
        <button>
          <img
            src="{% static 'social/icons/comment_icon.svg' %}"
            alt="Comment icon"
            width="20"
          />
        </button>
        <span id="commentsID-" class="ligthgray-text">0</span>
      </div>

      <div class="buttons-and-data">
        <button>
          <img
            src="{% static 'social/icons/share_icon.svg' %}"
            alt="Share icon"
            width="20"
          />
        </button>
        <span id="sharessID-" class="ligthgray-text">0</span>
      </div>

      <div class="buttons-and-data">
        <!-- Show the edit button only for the logged user that created the post -->
        {% if user.username == post.creator.username %}
        <button data-postid="{{post.id}}" class="edit-btn">Edit</button>
        {% endif %}
      </div>

      {% else %}
      <div class="buttons-and-data">
        <img
          src="{% static 'social/icons/like_icon.svg' %}"
          alt="Like icon"
          width="20"
        />
        <span id="likesID-{{post.id}}" class="ligthgray-text"
          >{{ post.likes }}</span
        >
      </div>

      <div class="buttons-and-data">
        <img
          src="{% static 'social/icons/comment_icon.svg' %}"
          alt="Comment icon"
          width="20"
        />
        <span id="commentsID-" class="ligthgray-text">0</span>
      </div>
      {% endif %}
    </div>
  </div>
  {% endfor %} {% if displayPagination %}
  <!-- Source: https://docs.djangoproject.com/en/3.0/topics/pagination/ -->
  <nav aria-label="Page navigation between posts">
    <!-- Aligning the pagination components in the middle with flexbox -->
    <ul class="pagination justify-content-center">
      {% if allPosts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ allPosts.previous_page_number }}"
          >&laquo;</a
        >
      </li>
      {% endif %}

      <li class="page-item">
        <a class="page-link" href="#">{{ allPosts.number }}</a>
      </li>

      {% if allPosts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ allPosts.next_page_number }}"
          >&raquo;</a
        >
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ allPosts.paginator.num_pages }}"
          >last</a
        >
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</section>
{% endblock %} {% block script %}
<script src="{% static 'social/social.js' %}"></script>
{% endblock %}

social/templates/social/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charste="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Social Network{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'landing_page/logos/cm-logo.png' %}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'social/styles.css' %}" rel="stylesheet" />
    {% block script %} {% endblock %}
  </head>
  <body>
    <div id="top-banner">
      <h2><strong>Social</strong></h2>
    </div>

    <main>
      <aside id="left-aside">
        <nav>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a id="all-posts" href="{% url 'social:index' %}"
                ><img
                  src="{% static 'social/icons/home_icon.svg' %}"
                  width="25"
                />All Posts</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'social:profile-page' user.username %}"
                ><img
                  src="{% static 'social/icons/profile_icon.svg' %}"
                  width="25"
                /><strong>Profile: {{ user.username }}</strong></a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'social:following' user.username %}"
                ><img
                  src="{% static 'social/icons/following_icon.svg' %}"
                  width="25"
                />Following</a
              >
            </li>
            <li class="nav-item">
              <div id="dropdown">
                <button id="dropdown-btn">
                  <img
                    src="{% static 'social/icons/more_icon.svg' %}"
                    width="25"
                  />More
                </button>
                <div id="dropdown-content">
                  <button id="settings-btn">Settings</button>
                  <button>
                    <a id="logout-btn" href="{% url 'social:logout' %}"
                      >Log Out</a
                    >
                  </button>
                </div>
              </div>
            </li>

            <li class="nav-item">
              <button id="main-post-btn">Post</button>
            </li>

            {% else %}
            <li class="nav-item">
              <a href="{% url 'social:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'social:register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </aside>

      <sction id="posts-container"> {% block body %} {% endblock %} </sction>

      <aside id="right-aside">
        <!-- source: https://weatherwidget.io/ -->
        <a
          class="weatherwidget-io"
          href="https://forecast7.com/en/45d50n73d57/montreal/"
          data-label_1="MONTREAL"
          data-label_2="WEATHER"
          data-theme="original"
          >MONTREAL WEATHER</a
        >
        <script>
          !(function (d, s, id) {
            var js,
              fjs = d.getElementsByTagName(s)[0];
            if (!d.getElementById(id)) {
              js = d.createElement(s);
              js.id = id;
              js.src = "https://weatherwidget.io/js/widget.min.js";
              fjs.parentNode.insertBefore(js, fjs);
            }
          })(document, "script", "weatherwidget-io-js");
        </script>
      </aside>
    </main>
  </body>
</html>

social/templates/social/login.html
{% extends "social/layout.html" %}

{% block title %} - Login {% endblock %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'social:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'social:register' %}">Register here.</a>

{% endblock %}

social/templates/social/profile.html
<!-- This is the profile page of each user -->
{% extends "social/layout.html" %}
{% load static %}

{% block title %} - Profile {% endblock %}

{% block body %}
	<table id="profile-page-header">
		<tr>
			<td><h3>{{ userProfileObject.username }}'s profile</h3></td>
			<td>
				<!-- Show the follow/unfollow button for a user that is not the one logged in -->
			    {% if loggedUser.username != userProfileObject.username %}
			    
			    	<!-- Show the follow or unfollow btn, given if the user is already followed -->
			    	{% if isFollowing %}
			    		<button id="unfollow-btn" value="{{ userProfileObject.username }}">Unfollow</button>
			    	{% else %}
						<button id="follow-btn" value="{{ userProfileObject.username }}">Follow</button>
			    	{% endif %}
					
				{% endif %}
			</td>
		</tr>
		<tr>
			<td>
				<table id="follow-table">
					<tr>
						<td class="follow-data"><b>{{ userProfileObject.number_of_followers }}</b></td>
						<td class="follow-data"><b>{{ userProfileObject.number_of_followings }}</b></td>
					</tr>
					<tr>
						<td class="follow-data">followers</td>
						<td class="follow-data">following</td>
					</tr>
				</table>
			</td>
			<td></td>
		</tr>
	</table>

	{% if loggedUser.username == userProfileObject.username %}
        <div id="new-post-view" class="div-border">
            <h4>New Post</h4>

            <form id="new-post-form">
                <!--{% csrf_token %} WILL IMPLEMENT THIS LATER exempt for now-->
                <textarea id="new-post" class="form-control" maxlength="280"></textarea>
                <input type="submit" class="btn btn-primary btn-sm" value="Post">
            </form>
        </div>
    {% endif %}

	{% for post in userPosts%}
        <div class="div-border">
            <p><b>{{ post.creator.username }}</b></p>
            <!-- Show the edit button if the profile's page belongs to the logged user -->
            {% if loggedUser.username == userProfileObject.username %}
                <button data-postid="{{post.id}}" class="edit-btn">Edit</button>
            {% endif %}
            <div id="postID-{{post.id}}">{{ post.post }}</div>
            <div class="ligthgray-text">{{ post.timestamp }}</div>
            <div>
                <button data-postid="{{post.id}}" class="like-btn">
                    <img src="{% static 'social/like-logo.png' %}" alt="Like logo" width="20">
                </button>
                <span id="likesID-{{post.id}}" class="ligthgray-text">{{ post.likes }}</span>
             </div>
            <!-- IMPLEMENT LATER<div>Comment</div>-->
        </div>
    {% endfor %} 

    {% if displayPagination %}
        <!-- Source: https://docs.djangoproject.com/en/3.0/topics/pagination/ -->
        <nav aria-label="Page navigation between posts">
            <!-- Aligning the pagination components in the middle with flexbox -->
            <ul class="pagination justify-content-center">  
                {% if userPosts.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ userPosts.previous_page_number }}">&laquo;</a></li>
                {% endif %}

                    <li class="page-item"><a class="page-link" href="#">{{ userPosts.number }}</a></li>

                {% if userPosts.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ userPosts.next_page_number }}">&raquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ userPosts.paginator.num_pages }}">last</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{% static 'social/social.js' %}"></script>
{% endblock %}

social/templates/social/register.html
{% extends "social/layout.html" %}

{% block title %} - Register {% endblock %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <!-- DISABLED REGISTER <form action="{% url 'social:register' %}" method="post"> -->
        <form>
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'social:login' %}">Log In here.</a>

{% endblock %}